# Generated by Django 5.0.4 on 2024-07-30 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abb_language', models.CharField(max_length=10, null=True, unique=True)),
                ('des_language', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('des_language_level', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'language_level',
            },
        ),
        migrations.CreateModel(
            name='ReasonToStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('des_reason_to_study', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'reason_to_study',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('des_topic', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_language_to_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_language_preferences', to='learning.language')),
                ('id_language_to_study_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.languagelevel')),
                ('id_native_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_language_preferences', to='learning.language')),
                ('id_reason_to_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.reasontostudy')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_preference',
                'unique_together': {('id_user', 'id_native_language', 'id_language_to_study', 'id_language_to_study_level', 'id_reason_to_study')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topic')),
                ('id_user_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.userpreference')),
            ],
            options={
                'db_table': 'user_preference_topic',
                'unique_together': {('id_user_preference', 'id_topic')},
            },
        ),
    ]
