# Generated by Django 5.0.4 on 2024-07-30 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('des_learning_phase', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'learning_phase',
            },
        ),
        migrations.CreateModel(
            name='LearningStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('des_learning_step', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'learning_step',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nam_deck', models.CharField(max_length=256)),
                ('new_cards_per_day', models.PositiveIntegerField(default=0)),
                ('gra_interval', models.PositiveIntegerField(default=24)),
                ('ste_value', models.PositiveIntegerField(default=10)),
                ('gra_max_interval', models.PositiveIntegerField(default=180)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'deck',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lap_card', models.BooleanField(default=False)),
                ('las_interval_card', models.IntegerField(default=0)),
                ('nex_interval_card', models.IntegerField(default=0)),
                ('eas_factor_card', models.IntegerField(default=250)),
                ('val_card', models.CharField(max_length=510)),
                ('mea_card', models.CharField(max_length=510)),
                ('day_added_card', models.DateTimeField()),
                ('fir_review_card', models.DateTimeField(null=True)),
                ('las_review_card', models.DateTimeField(null=True)),
                ('rev_card', models.PositiveIntegerField(default=0)),
                ('id_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.deck')),
                ('id_learning_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.learningphase')),
                ('id_last_learning_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.learningstep')),
            ],
            options={
                'db_table': 'card',
            },
        ),
    ]
