# Generated by Django 5.0.4 on 2024-07-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id_last_learning_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.learningstep'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id_learning_phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.learningphase'),
        ),
        migrations.AlterField(
            model_name='card',
            name='mea_card',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='card',
            name='val_card',
            field=models.CharField(max_length=512),
        ),
    ]
